version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "061206535013"
    REPOSITORY_NAME: "website"
    CONTAINER_NAME: "website"
    CLUSTER_NAME: "websiteclus"
    AWS_DEFAULT_REGION: "eu-north-1"
    IMAGE_TAG: "latest"
phases:
 pre_build:
  commands:
    - echo "Logging in to Amazon ECR..."
    - LOGIN_COMMAND=$(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - eval $LOGIN_COMMAND
    - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_NAME:$IMAGE_TAG .
      - docker tag $REPOSITORY_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
